# Generated by Django 5.2.11 on 2026-02-07 10:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, help_text='Logo for header (CHAYKOVSKA)', max_length=255, null=True, verbose_name='logo')),
                ('phone_number', models.CharField(default='+380', help_text='Primary phone number', max_length=20)),
                ('email', models.EmailField(default='info@chaykovska.com', help_text='Contact email', max_length=254)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
