# Generated by Django 5.2.11 on 2026-02-07 10:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('brand', 'Brand'), ('fabrics', 'Fabrics'), ('production', 'Production')], max_length=20, unique=True)),
                ('title', models.CharField(help_text='Section title (translatable)', max_length=200)),
                ('title_uk', models.CharField(help_text='Section title (translatable)', max_length=200, null=True)),
                ('title_en', models.CharField(help_text='Section title (translatable)', max_length=200, null=True)),
                ('content', models.TextField(help_text='Section content (translatable)')),
                ('content_uk', models.TextField(help_text='Section content (translatable)', null=True)),
                ('content_en', models.TextField(help_text='Section content (translatable)', null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(help_text='Showroom address (translatable)')),
                ('address_uk', models.TextField(help_text='Showroom address (translatable)', null=True)),
                ('address_en', models.TextField(help_text='Showroom address (translatable)', null=True)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(help_text='Contact email', max_length=254)),
                ('working_hours', models.TextField(help_text='Working hours (translatable)')),
                ('working_hours_uk', models.TextField(help_text='Working hours (translatable)', null=True)),
                ('working_hours_en', models.TextField(help_text='Working hours (translatable)', null=True)),
                ('map_url', models.URLField(blank=True, help_text='Google Maps embed URL', null=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='MosaicCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Cell position 1-12 (6 rows x 2 cols)', unique=True)),
                ('size_type', models.CharField(choices=[('half', 'Half Width (1 col)'), ('full_width', 'Full Width (2 cols)'), ('double_height', 'Double Height (2 rows)')], default='half', max_length=20)),
                ('image_1', cloudinary.models.CloudinaryField(help_text='First image to rotate', max_length=255, verbose_name='image_1')),
                ('image_2', cloudinary.models.CloudinaryField(help_text='Second image to rotate', max_length=255, verbose_name='image_2')),
                ('image_3', cloudinary.models.CloudinaryField(help_text='Third image to rotate', max_length=255, verbose_name='image_3')),
                ('link', models.URLField(blank=True, help_text='Optional: Where cell click navigates', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show or hide this cell')),
            ],
            options={
                'verbose_name': 'Mosaic Cell',
                'verbose_name_plural': 'Mosaic Cells',
                'ordering': ['position'],
            },
        ),
    ]
