# Generated by Django 6.0.2 on 2026-02-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosaiccell',
            name='slide_direction',
            field=models.CharField(choices=[('right', 'From Right → (new enters from right)'), ('left', 'From Left ← (new enters from left)'), ('top', 'From Top ↑ (new enters from top)'), ('bottom', 'From Bottom ↓ (new enters from bottom)')], default='right', help_text='Direction the new image enters from on hover', max_length=10),
        ),
    ]
