# Generated by Django 5.2.11 on 2026-02-07 10:51

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (translatable)', max_length=200)),
                ('name_uk', models.CharField(help_text='Category name (translatable)', max_length=200, null=True)),
                ('name_en', models.CharField(help_text='Category name (translatable)', max_length=200, null=True)),
                ('slug', models.SlugField(help_text='URL slug', unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name (translatable)', max_length=200)),
                ('name_uk', models.CharField(help_text='Product name (translatable)', max_length=200, null=True)),
                ('name_en', models.CharField(help_text='Product name (translatable)', max_length=200, null=True)),
                ('description', models.TextField(help_text='Product description (translatable)')),
                ('description_uk', models.TextField(help_text='Product description (translatable)', null=True)),
                ('description_en', models.TextField(help_text='Product description (translatable)', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in UAH', max_digits=10)),
                ('is_available', models.BooleanField(default=True, help_text='Is product available for purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(help_text='Product image', max_length=255, verbose_name='image')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['product', 'position'],
            },
        ),
    ]
