# Generated by Django 5.2.11 on 2026-02-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL slug (auto-generated from name)', unique=True),
        ),
    ]
