# Generated by Django 6.0.2 on 2026-02-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in EUR (European market)', max_digits=10, null=True),
        ),
    ]
